### ISSUE TITLE
Barra de Scroll

### ISSUE THREAD

**Issue by brunopurper** [anapolese/anapolese#1]
Oi Ana, a tua barra de scroll tu fez com o intuito de só aparecer depois que a pessoa clicar na setinha para baixo?

**Comment by anapolese** [comment]
Oii Bruno, siim ou para aparecer quando clica na seta, ou para quando você clica em alguma das opções do menu, queria deixar um pouco mais clean a home, a intenção futura é ainda colocar outras setas para cima nas outras páginas!

**Comment by brunopurper** [comment]
Ta ficando muito legal, adorei a estilização da scroll bar, top!
